package client_credential

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	res "github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/streamkap-com/terraform-provider-streamkap/internal/api"
)

var (
	_ res.Resource                = &ClientCredentialResource{}
	_ res.ResourceWithConfigure   = &ClientCredentialResource{}
	_ res.ResourceWithImportState = &ClientCredentialResource{}
)

func NewClientCredentialResource() res.Resource {
	return &ClientCredentialResource{}
}

type ClientCredentialResource struct {
	client api.StreamkapAPI
}

type RoleModel struct {
	ID          types.String `tfsdk:"id"`
	Key         types.String `tfsdk:"key"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
}

type ClientCredentialResourceModel struct {
	ID          types.String   `tfsdk:"id"`
	ClientID    types.String   `tfsdk:"client_id"`
	Secret      types.String   `tfsdk:"secret"`
	RoleIDs     []types.String `tfsdk:"role_ids"`
	Description types.String   `tfsdk:"description"`
	ServiceID   types.String   `tfsdk:"service_id"`
	CreatedAt   types.String   `tfsdk:"created_at"`
	Roles       []RoleModel    `tfsdk:"roles"`
}

func (r *ClientCredentialResource) Metadata(ctx context.Context, req res.MetadataRequest, resp *res.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_client_credential"
}

func (r *ClientCredentialResource) Schema(ctx context.Context, req res.SchemaRequest, resp *res.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Streamkap client credential (API token) for machine-to-machine authentication.",
		MarkdownDescription: "Manages a **Streamkap client credential** (API token) for machine-to-machine authentication.\n\n" +
			"Client credentials are used to authenticate API access programmatically. " +
			"The secret is only returned on creation and cannot be retrieved afterwards.\n\n" +
			"**Note:** This resource does not support updates. Any change to configuration will " +
			"destroy the existing credential and create a new one.\n\n" +
			"[Documentation](https://docs.streamkap.com/api-tokens)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:         "Unique identifier for the client credential. Same as client_id.",
				MarkdownDescription: "Unique identifier for the client credential. Same as `client_id`.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"client_id": schema.StringAttribute{
				Description:         "The client ID for this credential. Generated by the server.",
				MarkdownDescription: "The client ID for this credential. Generated by the server.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"secret": schema.StringAttribute{
				Description:         "The client secret. Only returned on creation and stored in state. This value is sensitive and will not appear in logs or CLI output.",
				MarkdownDescription: "The client secret. Only returned on creation and stored in state.\n\n**Security:** This value is marked sensitive and will not appear in CLI output or logs.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"role_ids": schema.ListAttribute{
				Description:         "List of role IDs to assign to this client credential. At least one role is required. Cannot be changed after creation.",
				MarkdownDescription: "List of role IDs to assign to this client credential. At least one role is required. **Cannot be changed after creation.**",
				Required:            true,
				ElementType:         types.StringType,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
			"description": schema.StringAttribute{
				Description:         "Optional description of the client credential's purpose. Cannot be changed after creation.",
				MarkdownDescription: "Optional description of the client credential's purpose. **Cannot be changed after creation.**",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"service_id": schema.StringAttribute{
				Description:         "Optional service ID to associate with this credential. Cannot be changed after creation.",
				MarkdownDescription: "Optional service ID to associate with this credential. **Cannot be changed after creation.**",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.StringAttribute{
				Description:         "Timestamp when the credential was created. Computed by the server.",
				MarkdownDescription: "Timestamp when the credential was created. Computed by the server.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"roles": schema.ListNestedBlock{
				Description:         "Resolved role objects assigned to this credential. Computed by the server.",
				MarkdownDescription: "Resolved role objects assigned to this credential. Computed by the server.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description:         "Role ID.",
							MarkdownDescription: "Role ID.",
							Computed:            true,
						},
						"key": schema.StringAttribute{
							Description:         "Role key identifier.",
							MarkdownDescription: "Role key identifier.",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							Description:         "Role display name.",
							MarkdownDescription: "Role display name.",
							Computed:            true,
						},
						"description": schema.StringAttribute{
							Description:         "Role description.",
							MarkdownDescription: "Role description.",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (r *ClientCredentialResource) Configure(ctx context.Context, req res.ConfigureRequest, resp *res.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(api.StreamkapAPI)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Client Credential Configure Type",
			fmt.Sprintf("Expected api.StreamkapAPI, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *ClientCredentialResource) Create(ctx context.Context, req res.CreateRequest, resp *res.CreateResponse) {
	var plan ClientCredentialResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	roleIDs := make([]string, len(plan.RoleIDs))
	for i, r := range plan.RoleIDs {
		roleIDs[i] = r.ValueString()
	}

	cred, err := r.client.CreateClientCredential(ctx, api.CreateClientCredentialRequest{
		RoleIDs:     roleIDs,
		Description: plan.Description.ValueString(),
		ServiceID:   plan.ServiceID.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error creating client credential", fmt.Sprintf("Unable to create client credential: %s", err))
		return
	}

	r.modelFromAPIObject(cred, &plan)
	// Secret is only available on creation
	plan.Secret = types.StringValue(cred.Secret)
	tflog.Info(ctx, "Created client credential: "+cred.ClientID)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *ClientCredentialResource) Read(ctx context.Context, req res.ReadRequest, resp *res.ReadResponse) {
	var state ClientCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	cred, err := r.client.GetClientCredential(ctx, state.ClientID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading client credential", fmt.Sprintf("Unable to read client credential: %s", err))
		return
	}
	if cred == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	// Preserve the secret from state since API doesn't return it on reads
	secret := state.Secret
	r.modelFromAPIObject(cred, &state)
	state.Secret = secret
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ClientCredentialResource) Update(ctx context.Context, req res.UpdateRequest, resp *res.UpdateResponse) {
	// No Update API exists — all writable fields are ForceNew, so this should never be called.
	resp.Diagnostics.AddError(
		"Update not supported",
		"Client credentials cannot be updated. Any change requires destroying and recreating the resource.",
	)
}

func (r *ClientCredentialResource) Delete(ctx context.Context, req res.DeleteRequest, resp *res.DeleteResponse) {
	var state ClientCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteClientCredential(ctx, state.ClientID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error deleting client credential", fmt.Sprintf("Unable to delete client credential: %s", err))
		return
	}
	tflog.Info(ctx, "Deleted client credential: "+state.ClientID.ValueString())
}

func (r *ClientCredentialResource) ImportState(ctx context.Context, req res.ImportStateRequest, resp *res.ImportStateResponse) {
	// Import ID is the client_id
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("client_id"), req.ID)...)
}

// modelFromAPIObject maps API response to Terraform model.
// Note: Secret is intentionally not set here — it is write-only (only returned on creation).
// The caller must handle Secret preservation separately.
func (r *ClientCredentialResource) modelFromAPIObject(apiObject *api.ClientCredential, model *ClientCredentialResourceModel) {
	model.ID = types.StringValue(apiObject.ClientID)
	model.ClientID = types.StringValue(apiObject.ClientID)
	model.Description = types.StringValue(apiObject.Description)
	model.CreatedAt = types.StringValue(apiObject.CreatedAt)
	model.ServiceID = types.StringValue(apiObject.ServiceID)

	roles := make([]RoleModel, len(apiObject.Roles))
	for i, role := range apiObject.Roles {
		roles[i] = RoleModel{
			ID:          types.StringValue(role.ID),
			Key:         types.StringValue(role.Key),
			Name:        types.StringValue(role.Name),
			Description: types.StringValue(role.Description),
		}
	}
	model.Roles = roles

	// Extract role_ids from the resolved roles in the same pass
	roleIDs := make([]types.String, len(apiObject.Roles))
	for i := range roles {
		roleIDs[i] = roles[i].ID
	}
	model.RoleIDs = roleIDs
}
