# Complete Salesforce Webhook source configuration
# Receives Salesforce Change Data Capture / Platform Events over a Streamkap-issued
# webhook endpoint, and snapshots existing objects through the Salesforce REST API.

terraform {
  required_providers {
    streamkap = {
      source  = "streamkap-com/streamkap"
      version = "3.0.0-beta.30"
    }
  }
  required_version = ">= 1.5.0"
}

provider "streamkap" {}

resource "streamkap_source_salesforce_webhook" "example" {
  # Display name for this source in the Streamkap UI
  name = "example-source-salesforce-webhook"

  # Note: webhook_url and api_key are generated by Streamkap after creation and
  # are exposed as computed attributes (see the outputs below).

  # Salesforce Connected App credentials, used for the initial snapshot.
  # The generated schema marks these Optional (the backend ships them as
  # required-with-default, which Terraform demotes to Optional+Computed), but a
  # connector without them is unusable at runtime — always set them.
  camel_source_snapshot_salesforce_instance_url       = "https://your-org.my.salesforce.com"
  camel_source_snapshot_salesforce_auth_client_id     = var.salesforce_client_id
  camel_source_snapshot_salesforce_auth_client_secret = var.salesforce_client_secret
  camel_source_snapshot_salesforce_auth_username      = var.salesforce_username
  camel_source_snapshot_salesforce_auth_password      = var.salesforce_password

  # Salesforce objects to ingest. Defaults to "Account,Contact,Lead,Opportunity".
  topic_include_list = "Account,Contact,Lead,Opportunity"

  # Stream Change Data Capture events in addition to the snapshot. Defaults to true.
  camel_source_cdc_enabled = true

  # Routing of payloads whose type is not in topic_include_list.
  camel_source_payload_router_unknown_type_behavior      = "DEFAULT_TOPIC" # Options: DEFAULT_TOPIC, SKIP, FAIL
  camel_source_payload_router_unknown_type_default_topic = "unknown"

  # Flatten the nested payload detail into top-level fields. Defaults to true.
  camel_source_payload_router_flatten_detail        = true
  camel_source_payload_router_flatten_detail_prefix = ""

  # Keep the raw event envelope alongside the flattened detail. Defaults to false.
  camel_source_payload_router_include_event = false

  # Route un-processable messages to a dead-letter queue. Defaults to true.
  camel_source_dlq_enabled = true

  # Promote value fields into the Kafka record key
  transforms_value_to_key_fields_include_list       = "Id"
  transforms_value_to_key_replace_null_with_default = true

  # Emit null-valued fields instead of omitting them. Defaults to false.
  preserve_null_values = false

  # Oversized-record handling
  transforms_oversized_records_max_field_size_bytes      = 1048576
  transforms_oversized_records_oversized_field_behavior  = "TRUNCATE" # Options: TRUNCATE, NULLIFY
  transforms_oversized_records_truncation_suffix         = ""
  transforms_oversized_records_max_record_size_bytes     = -1 # -1 disables the overall limit
  transforms_oversized_records_semantic_types_exclude    = "io.debezium.data.Json,io.debezium.data.Xml"
  transforms_oversized_records_replace_null_with_default = true

  # Add a _streamkap_topic field carrying the Kafka topic name. Required if a
  # topic_router transform sits downstream. Defaults to false.
  insert_topic_name_enabled = false
}

variable "salesforce_client_id" {
  type        = string
  description = "Salesforce Connected App consumer key (client_id)."
}

variable "salesforce_client_secret" {
  type        = string
  sensitive   = true
  description = "Salesforce Connected App consumer secret (client_secret)."
}

variable "salesforce_username" {
  type        = string
  description = "Salesforce API username used for the snapshot."
}

variable "salesforce_password" {
  type        = string
  sensitive   = true
  description = "Salesforce API password (plus security token, if required)."
}

output "example-source-salesforce-webhook-id" {
  value = streamkap_source_salesforce_webhook.example.id
}

# Point the Salesforce webhook at this URL
output "example-source-salesforce-webhook-url" {
  value       = streamkap_source_salesforce_webhook.example.webhook_url
  description = "The webhook URL Salesforce should POST to."
}

output "example-source-salesforce-webhook-api-key" {
  value       = streamkap_source_salesforce_webhook.example.api_key
  description = "API key required on requests to the webhook URL."
  sensitive   = true
}
