# Complete Zendesk Webhook source configuration
# Receives Zendesk events on a Streamkap-issued webhook endpoint.

terraform {
  required_providers {
    streamkap = {
      source  = "streamkap-com/streamkap"
      version = ">= 2.0.0"
    }
  }
  required_version = ">= 1.5.0"
}

provider "streamkap" {}

resource "streamkap_source_zendesk_webhook" "example" {
  # Display name for this source in the Streamkap UI
  name = "example-source-zendesk-webhook"

  # Note: webhook_url and api_key are generated by Streamkap after creation and
  # are exposed as computed attributes (see the outputs below).

  # Routing of payloads whose type Streamkap does not recognise.
  camel_source_payload_router_unknown_type_behavior      = "DEFAULT_TOPIC" # Options: DEFAULT_TOPIC, SKIP, FAIL
  camel_source_payload_router_unknown_type_default_topic = "unknown"

  # Flatten the nested payload detail into top-level fields. Defaults to true.
  camel_source_payload_router_flatten_detail        = true
  camel_source_payload_router_flatten_detail_prefix = "detail_"

  # Keep the raw event envelope alongside the flattened detail. Defaults to false.
  camel_source_payload_router_include_event = false

  # Domain-scoped array fields to fan out into their own topics.
  # Empty (the default) keeps arrays inline.
  camel_source_payload_router_fanout_fields = "ticket.tags,ticket.custom_fields"

  # Route un-processable messages to a dead-letter queue. Defaults to true.
  camel_source_dlq_enabled = true

  # Promote value fields into the Kafka record key
  transforms_value_to_key_fields_include_list       = "id"
  transforms_value_to_key_replace_null_with_default = true

  # Emit null-valued fields instead of omitting them. Defaults to false.
  preserve_null_values = false

  # Oversized-record handling
  transforms_oversized_records_max_field_size_bytes      = 1048576
  transforms_oversized_records_oversized_field_behavior  = "TRUNCATE" # Options: TRUNCATE, NULLIFY
  transforms_oversized_records_truncation_suffix         = ""
  transforms_oversized_records_max_record_size_bytes     = -1 # -1 disables the overall limit
  transforms_oversized_records_semantic_types_exclude    = "io.debezium.data.Json,io.debezium.data.Xml"
  transforms_oversized_records_replace_null_with_default = true

  # Add a _streamkap_topic field carrying the Kafka topic name. Required if a
  # topic_router transform sits downstream. Defaults to false.
  insert_topic_name_enabled = false
}

output "example-source-zendesk-webhook-id" {
  value = streamkap_source_zendesk_webhook.example.id
}

# Point the Zendesk webhook target at this URL
output "example-source-zendesk-webhook-url" {
  value       = streamkap_source_zendesk_webhook.example.webhook_url
  description = "The webhook URL Zendesk should POST to."
}

output "example-source-zendesk-webhook-api-key" {
  value       = streamkap_source_zendesk_webhook.example.api_key
  description = "API key required on requests to the webhook URL."
  sensitive   = true
}
