#! /bin/bash
# Source PostgreSQL
export SOURCE_POSTGRESQL_HOSTNAME=""
export SOURCE_POSTGRESQL_PASSWORD=''

# Destination Snowflake
export DESTINATION_SNOWFLAKE_URL_NAME=""
export DESTINATION_SNOWFLAKE_PRIVATE_KEY=''
export DESTINATION_SNOWFLAKE_KEY_PASSPHRASE=""
