package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSourceWebhookResource(t *testing.T) {
	name := acctestName(t, "main")
	nameUpdated := acctestName(t, "updated")

	// Webhook source has no external credentials required - it generates webhook_url and api_key
	// Skip only if TF_ACC is not set (handled by framework) or if explicitly disabled
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckSourceDestroy,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: providerConfig + fmt.Sprintf(`
resource "streamkap_source_webhook" "test" {
	name                                    = %q
	topic_include_list                      = "webhook_events"
	format                                  = "json"
	camel_source_camel_message_header_key   = "key"
	transforms_infer_schema_add_delete_field = false
}
`, name),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "name", name),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "topic_include_list", "webhook_events"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "format", "json"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "camel_source_camel_message_header_key", "key"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "transforms_infer_schema_add_delete_field", "false"),
					// webhook_url and api_key are generated by the backend after creation
					resource.TestCheckResourceAttrSet("streamkap_source_webhook.test", "id"),
				),
			},
			// ImportState testing
			{
				ResourceName:            "streamkap_source_webhook.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_status"},
			},
			// Update and Read testing
			{
				Config: providerConfig + fmt.Sprintf(`
resource "streamkap_source_webhook" "test" {
	name                                    = %q
	topic_include_list                      = "webhook_events_updated"
	format                                  = "string"
	camel_source_camel_message_header_key   = "event_key"
	transforms_infer_schema_add_delete_field = true
}
`, nameUpdated),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "name", nameUpdated),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "topic_include_list", "webhook_events_updated"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "format", "string"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "camel_source_camel_message_header_key", "event_key"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "transforms_infer_schema_add_delete_field", "true"),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}
