package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSourceWebhookResource(t *testing.T) {
	// Webhook source has no external credentials required - it generates webhook_url and api_key
	// Skip only if TF_ACC is not set (handled by framework) or if explicitly disabled
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: providerConfig + `
resource "streamkap_source_webhook" "test" {
	name                                    = "tf-acc-test-source-webhook"
	topic_include_list                      = "webhook_events"
	format                                  = "json"
	camel_source_camel_message_header_key   = "key"
	transforms_infer_schema_add_delete_field = false
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "name", "tf-acc-test-source-webhook"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "topic_include_list", "webhook_events"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "format", "json"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "camel_source_camel_message_header_key", "key"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "transforms_infer_schema_add_delete_field", "false"),
					// webhook_url and api_key are generated by the backend after creation
					resource.TestCheckResourceAttrSet("streamkap_source_webhook.test", "id"),
				),
			},
			// ImportState testing
			{
				ResourceName:      "streamkap_source_webhook.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update and Read testing
			{
				Config: providerConfig + `
resource "streamkap_source_webhook" "test" {
	name                                    = "tf-acc-test-source-webhook-updated"
	topic_include_list                      = "webhook_events_updated"
	format                                  = "string"
	camel_source_camel_message_header_key   = "event_key"
	transforms_infer_schema_add_delete_field = true
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "name", "tf-acc-test-source-webhook-updated"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "topic_include_list", "webhook_events_updated"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "format", "string"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "camel_source_camel_message_header_key", "event_key"),
					resource.TestCheckResourceAttr("streamkap_source_webhook.test", "transforms_infer_schema_add_delete_field", "true"),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}
